### ISSUE TITLE
addState options should be well defined

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/abstract-state-router#24]
It's not clear from the documentation which `addState()` options are required.

As far as I know, these are required: **name, template, activate** and these are not: *route, defaultChild, data, resolve, querystringParameters*

This should be documented. (Or fixed if this is not the desired case.)

Should an error be thrown when attempting to add a state without all of the required parameters?

**Comment by TehShrike** [comment]
I think you get errors if you don't include activate right now, but it shouldn't be required.

- Should be required: *name, template*
- Should be optional: *activate, route, defaultChild, data, resolve, querystringParameters*

And yeah, we should have immediate friendly errors when you try to add a state, instead of things probably breaking later when you don't provide the required properties.
