### ISSUE TITLE
url not found 404 error handling

### ISSUE THREAD

**Issue by AgentChris** [TehShrike/abstract-state-router#60]
How can I handle the urls that are not found?

**Comment by TehShrike** [comment]
The state router will emit a `stateChangeError` event that you can handle: https://github.com/TehShrike/abstract-state-router/blob/master/index.js#L321

This doesn't appear to be documented under [events](https://github.com/TehShrike/abstract-state-router#events) yet! :-x

**Comment by TehShrike** [comment]
If you're talking about someone manually editing the url to something invalid, that isn't handled at the moment.  That should probably be implemented by adding something like
```js
stateRouterOptions.router.setDefault(function(path, parameters) {
  stateProviderEmitter.emit('routeNotFound', path, parameters)
})
```

Router method: https://github.com/TehShrike/hash-brown-router/#routersetdefaultcb---set-a-default404-route

A pull request with a test/implementation would be appreciated, otherwise I'll get to this at some point.

**Comment by TehShrike** [comment]
Failed test added in https://github.com/TehShrike/abstract-state-router/commit/17f5a3ce5945ae9b2b0cffe336ed415de76f6f4e and fixed by https://github.com/TehShrike/abstract-state-router/commit/f3e2fbda5fa85068df3aa9f9539d61bb95667caf and published as 15.12.0!  Let me know what you think.

**Comment by TehShrike** [comment]
...and some more documentation added in https://github.com/TehShrike/abstract-state-router/commit/71c33045db15b66b018c5cafedf27a8bf46be1c0

**Comment by AgentChris** [comment]
works perfectly thanks :+1:
