### ISSUE TITLE
Edge case where no activate function gets called after a redirect

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/abstract-state-router#74]
- [Download these files](https://gist.github.com/ArtskydJ/71ebacc01a583bbdee8b78385f7ff1b3/archive/f51ce50389ef58c1f2dafdf4c334b5b1eb6d156b.zip) and host them on localhost.
- Run `npm run watch`
- Go to `http://localhost:8080/asr-rbtc/#/` which causes an stateChangeError, and the screen stays blank, and no activate function gets called. (There is not a route for `/`.)
- Going to ``http://localhost:8080/asr-rbtc/` worked fine (and went to the 404 page because of evaluateCurrentRoute)

**Comment by TehShrike** [comment]
Both the alpha and bravo states are implicitly at route `/` because they don't have any parents with a route, and they don't have any route, [and empty strings are treated as `/`](https://github.com/TehShrike/abstract-state-router/blob/8756a45219510ae9702ee52b0a33601318eb443d/lib/state-state.js#L47-L51).

All state transitions are triggered by a url change, so when the alpha state loads (prompted by navigating to the `/` route) and tries to initiate a transfer to the bravo state, it attempts to change the url... to `/`.  Which doesn't trigger any "route changed" events, because it was already at that route.  (And if it did trigger a route changed event, it would just load alpha again, because that's the first state at that route).

If you give the bravo state a route, and then load `#/`, it redirects to `#/bravo` and loads the state correctly.

**Comment by ArtskydJ** [comment]
If this is a user-error, I can accept that. Ideally, if we can note it in a simple way in the readme, that might be nice.

Does this mean that it is unsupported to navigate to another state with the same route? Right now I get this error:

```js
router.on('stateChangeCancelled', e => console.log(e.message)) // => "This probably shouldn't happen, open an issue or something"
```

Maybe I should get an error like:

```js
router.on('stateChangeCancelled', e => console.log(e.message)) // => "Unable to navigate to a state with the same route"
```

**Comment by TehShrike** [comment]
I think the reason you got that error is because you were `throw`ing inside of the event handlers for the state change cancel/error, not because of the duplicate routes.

I'm not sure what an appropriate warning would be in this case - maybe "you attempted to navigate to route `/` but you were already there"?  Maybe the hash-brown-router could emit an error or something if there were multiple handlers found for a route?
